// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGO8y9QRn69NFi30zHgCC-mLHmAOF0u8k',
    appId: '1:835950835552:web:c69fa168f4831e426e9005',
    messagingSenderId: '835950835552',
    projectId: 'super-chat-ec589',
    authDomain: 'super-chat-ec589.firebaseapp.com',
    storageBucket: 'super-chat-ec589.appspot.com',
    measurementId: 'G-03E0CHPZH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vNq1hkwPZdSdj1rbcjUgPzu3rxT-o88',
    appId: '1:835950835552:android:3cef38db17d5c6ab6e9005',
    messagingSenderId: '835950835552',
    projectId: 'super-chat-ec589',
    storageBucket: 'super-chat-ec589.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmVmq3_zNzznHJCr5YK9uxJ2PiOq7g6gI',
    appId: '1:835950835552:ios:4fed9f7004c812bf6e9005',
    messagingSenderId: '835950835552',
    projectId: 'super-chat-ec589',
    storageBucket: 'super-chat-ec589.appspot.com',
    iosClientId: '835950835552-1ku7joquplt5hhjf2ldjdn3kbcqkravl.apps.googleusercontent.com',
    iosBundleId: 'com.seryxconcepts.superChat',
  );
}
